name: CI

on:
  pull_request:
  push:
    branches:
      - main 

concurrency:
  group: ci-${{ github.head_ref }}-${{ github.event_name }}
  cancel-in-progress: true
      
jobs:
  build:
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    
    steps:
      - uses: actions/checkout@v4
    
      - name: Build
        run: |
          bazel build //...
    
      - name: Test
        run: |
          bazel test --test_output=errors //...
          
  license-headers:
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    
    steps:
      - uses: actions/checkout@v4
      - run: ./scripts/license_check.sh 
